budgetiser/android/app/build.gradle, budgetiser/android/app/proguard-rules.pro, budgetiser/lib/config/themes/themes.dart, budgetiser/lib/drawer.dart, budgetiser/lib/screens/account/account_form.dart, budgetiser/lib/screens/categories/category_form.dart, budgetiser/lib/screens/create_db_screen.dart, budgetiser/lib/screens/groups/group_form.dart, budgetiser/lib/screens/plans/budget_form.dart, budgetiser/lib/screens/plans/saving_form.dart, budgetiser/lib/screens/settings_screen.dart, budgetiser/lib/screens/transactions/transaction_form.dart, budgetiser/lib/shared/dataClasses/transaction_category.dart, budgetiser/lib/shared/widgets/items/accountItem/account_item.dart, budgetiser/lib/shared/widgets/smallStuff/balance_text.dart, budgetiser/pubspec.yaml
- remove linter warnings
- fix release mode with sqflite_sqlcipher
=> cleanup warnings and fix release mode

lib/screens/transactions/transaction_form.dart
=> add transaction prefix button

lib/config/themes/themes.dart, lib/screens/account/account_form.dart, lib/screens/account/account_screen.dart, lib/screens/categories/category_form.dart, lib/screens/create_db_screen.dart, lib/screens/groups/group_form.dart, lib/screens/login.dart, lib/screens/notes_screen.dart, lib/screens/plans/budget_form.dart, lib/screens/plans/saving_form.dart, lib/screens/settings_screen.dart, lib/screens/transactions/transaction_form.dart, lib/screens/transactions/transactions_screen.dart, lib/shared/picker/color_picker.dart, lib/shared/picker/date_picker.dart, lib/shared/picker/select_icon.dart, lib/shared/widgets/confirmation_dialog.dart
- refactor and upgrade themes.dart to material3
- new colorpicker
=> 135 scroling animation

lib/config/themes/themes.dart, lib/db/account_part.dart, lib/db/single_transaction_part.dart, lib/screens/account/account_form.dart, lib/screens/account/account_screen.dart, lib/screens/transactions/transactions_screen.dart, lib/shared/dataClasses/single_transaction.dart, lib/shared/widgets/items/transaction_item.dart
Sadly no text when list is empty ;)
=> 103 transactions in monthly cards

lib/drawer.dart, lib/screens/categories/categories_screen.dart, lib/screens/groups/groups_screen.dart, lib/screens/transactions/transaction_form.dart, lib/screens/transactions/transactions_screen.dart, lib/shared/widgets/items/budget_item.dart, lib/shared/widgets/items/category_item.dart, lib/shared/widgets/items/group_item.dart, lib/shared/widgets/items/saving_item.dart, lib/shared/widgets/items/transaction_item.dart, lib/shared/widgets/smallStuff/linear_progress_bar.dart
=> Fix big text UI

lib/routes.dart, lib/screens/settings/about.dart, lib/screens/settings/settings_screen.dart, pubspec.yaml
=> 110 add about in settings

lib/shared/picker/select_account.dart, pubspec.yaml
App crashing when enabling 2nd account and recent account is the first account.
=> fix 2nd account recently used

lib/screens/transactions/transaction_form.dart, lib/shared/dataClasses/account.dart, lib/shared/dataClasses/budget.dart, lib/shared/dataClasses/group.dart, lib/shared/dataClasses/single_transaction.dart, lib/shared/dataClasses/transaction_category.dart, lib/shared/picker/select_account.dart, lib/shared/widgets/items/accountItem/account_item.dart, lib/shared/widgets/smallStuff/visualize_transaction.dart
- fix validation
- extracted transaction visualisation
- fix [bug] select the same account twice
- add default transaction title (categorie name)
=> 158 transaction form validation

lib/screens/transactions/transactions_screen.dart
you can now also click on the name when selecting
=> increase inkwell on transaction filter

lib/screens/settings/settings_screen.dart
=> Currency settings

lib/screens/account/account_screen.dart, lib/screens/budgets/budgets_screen.dart, lib/screens/categories/categories_screen.dart, lib/shared/widgets/itemLists/account_items_widget.dart, lib/shared/widgets/itemLists/item_list_container.dart, lib/shared/widgets/itemLists/item_list_divider.dart, lib/shared/widgets/items/budget_item.dart
and move BudgetItem to own file
=> use ListView.separated with ItemListDivider 

README-dev.md, lib/accounts/screens/account_screen.dart, lib/accounts/widgets/account_item.dart, lib/budgets/screens/budgets_screen.dart, lib/budgets/widgets/budget_item.dart, lib/categories/screens/categories_screen.dart, lib/categories/widgets/category_item.dart, lib/help/screens/help.dart, lib/home/screens/home_screen.dart, lib/notes/screens/notes_screen.dart, lib/settings/preferences/widgets/toggle_prefix_button.dart, lib/settings/screens/settings_screen.dart, lib/shared/widgets/actionButtons/cancel_action_button.dart, lib/shared/widgets/arrow_icon.dart, lib/shared/widgets/balance_text.dart, lib/shared/widgets/divider_with_text.dart, lib/shared/widgets/forms/custom_input_field.dart, lib/shared/widgets/forms/radio_item_clickable.dart, lib/shared/widgets/list_views/item_list_divider.dart, lib/shared/widgets/selectable/selectable_icon.dart, lib/shared/widgets/selectable/selectable_icon_with_text.dart, lib/shared/widgets/sort_by.dart, lib/statistics/screens/stats.dart, lib/transactions/screens/transaction_form.dart, lib/transactions/screens/transactions_screen.dart, lib/transactions/widgets/transaction_item.dart, lib/transactions/widgets/visualize_transaction_small.dart
- fix overflow
Also (not related to issue)
- harmonize doc string and constructor placement
=> Fix overflow on SelectableIconWithText

lib/core/database/database.dart, lib/transactions/screens/transaction_form.dart, lib/transactions/screens/transactions_screen.dart, pubspec.yaml
=> Hotfix: im-/export json

android/app/build.gradle, android/build.gradle, android/settings.gradle
done with https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
=> feat: migrate to gradle plugins

lib/transactions/screens/transactions_screen.dart, pubspec.lock, pubspec.yaml
=> feat: add badges to transaction screen filter

lib/accounts/widgets/account_item.dart, lib/budgets/screens/budget_form.dart, lib/budgets/widgets/budget_item.dart, lib/main.dart, lib/shared/widgets/forms/custom_input_field.dart, lib/shared/widgets/picker/selectable/multi_picker.dart, lib/statistics/screens/stat_preview_widget.dart, lib/transactions/widgets/transaction_item.dart
- consistent border radius
- better category picker in budgets
- change to listTile for 'all' selection
- custom themeData for listTile
| | | |
|-|-|-|
| ![Screenshot_1720558796](https://github.com/budgetiser/budgetiser/assets/75438446/b93effc4-09f8-42b8-93c7-6f73a9a7a2d1) | ![Screenshot_1720558785](https://github.com/budgetiser/budgetiser/assets/75438446/5905d2f7-b0f7-41b1-9980-4570bceb7cd8) | |
=> Material 3 refinement

lib/accounts/screens/account_screen.dart, lib/categories/widgets/category_tree.dart, lib/core/drawer.dart, lib/transactions/screens/transactions_screen.dart
- fix padding
| | | |
|-|-|-|
| | | |
=> fix: missing padding in list view

.github/workflows/release-internal.yml, .github/workflows/release-production.yml, pubspec.yaml
=> fix(ci): upgrade action version

android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle, lib/core/database/models/account.dart, lib/core/database/models/budget.dart, lib/core/database/models/category.dart, lib/shared/utils/color_utils.dart, pubspec.lock, pubspec.yaml, test/db_json_test.dart
flutter release 3.27
- upgrade packages and gradle version
=> Flutter update

.github/workflows/flutter-tests.yml, test/db_json_test.dart
- use workaround for color-compare
- fix linux action runner sqflite packages
| | | |
|-|-|-|
| | | |
=> Fix unit test

lib/categories/screens/category_form.dart
- add duplicate name check
- instant feedback while typing
- does not block form submission
- a bit ugly with 2 different form validators
| ![Screenshot_1736890392](https://github.com/user-attachments/assets/c8662c63-5aaa-4b6f-86a9-28ef8f55f957) | | |
|-|-|-|
| | | |
=> feat(category): add duplicate name check

.github/workflows/test-build.yml, android/gradle.properties, lib/shared/widgets/picker/icon_color/color_list.dart, lib/transactions/widgets/transaction_expansion_tile.dart, pubspec.lock, pubspec.yaml
- update flutter, dependencies
- fix deprecated functions
=> Dependencies

.github/workflows/release-internal.yml, .github/workflows/stale-issues.yaml
- internal release ci: 
- also upload apk to github release
- use main as release branch
- add stale issue marking
=> ci: upload file in release
